# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [8]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [23]:
A = np.arange(1, 16).reshape(3,5)

In [25]:
print("Dimension (Number of axes):", A.ndim)
print("Shape:", A.shape)
print("Size:", A.size)
print("Datatype:", A.dtype)

Dimension (Number of axes): 2
Shape: (3, 5)
Size: 15
Datatype: int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [27]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print(C)

elementwise_subtraction = B - C
print("\nElementwise subtraction")
print(elementwise_subtraction)

elementwise_multiplication = B * C
print("\nElementwise multiplication")
print(elementwise_multiplication)

matrix_multiplication = B @ C
print("\nMatrix Multiplication")
print(matrix_multiplication)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

Elementwise subtraction
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise multiplication
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix Multiplication
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [29]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [89]:
#exp
exp_B = np.exp(B)
print("Exponentiated")
print(exp_B)

#min
min_value = np.min(B)
print("\nMinimum value in the matrix")
print(min_value)

#min value in each row
min_value_row = np.min(B, axis=1)
print("\nMinimum value in each row")
print(min_value_row)

#min value in each column
min_value_col = np.min(B, axis=0)
print("\nMinimum value in each column")
print(min_value_col)

#index of the min value in the matrix
index_min = np.argmin(B)
print("\nIndex of the minimum value in the matrix")
print(index_min)

#index of the min value in each row
index_min_row = np.argmin(B, axis=1)
print("\nIndex of the minimum value in each row")
print(index_min_row)

#calculate the sum for all elements
sum_ele = np.sum(B)
print("\nSum for all elements")
print(sum_ele)

#calculate the mean for each column
mean_col = np.mean(B, axis=0)
print("\nMean of each column")
print(mean_col)

#calculate the median for each column
median_col = np.median(B, axis=0)
print("\nMedian of each column")
print(median_col)

Exponentiated
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value in the matrix
1

Minimum value in each row
[1 4 7]

Minimum value in each column
[1 2 3]

Index of the minimum value in the matrix
0

Index of the minimum value in each row
[0 0 0]

Sum for all elements
45

Mean of each column
[4. 5. 6.]

Median of each column
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [91]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [101]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer: A[1] skriver ut andra raden i matrisen, skriver vi A[0] så får vi ut första raden i matrisen och skriver vi A[2] får vi ut tredje raden i matrisen, detta är pågrund att vi har en 2-D Array. indexet börjar även på 0!**

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [107]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [109]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [113]:
#using np.editer allows it to iterate over each element in the array
for x in np.nditer(A):
    print(x, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 

### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [135]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


* Svar: a skriver ut en array med elementen 0 till 29 och b formar om arrayen till en 3-D Array där första axeln beskriver antalet matriser,
andra axeln beskriver hur många rader matriserna har och sista axeln beskriver hur många kolumner det ska finnas då det igentligen ska stå 5 men
med -1 så kalkylerar den snabbt själv vad som behövs så slipper man själv räkna på det.

In [153]:
test = a.reshape((3, 2, 5))
print(test)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [171]:
test2 = a.reshape((6, 1, -1))
print(test2)

[[[ 0  1  2  3  4]]

 [[ 5  6  7  8  9]]

 [[10 11 12 13 14]]

 [[15 16 17 18 19]]

 [[20 21 22 23 24]]

 [[25 26 27 28 29]]]


# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [185]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [187]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [189]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

#  Uppgift 10.1.1 Definiera vektorn x enligt nedan. x=(4,3)
* (a) Vilken dimension har vektorn x?
* Svar: 1x2, x har 1 rad och 2 kolumner

* (b) Beräkna 5x.

In [38]:
x = np.array([4, 3])
svar = 5 * x
svar

array([20, 15])

* (c) Beräkna 3x.

In [45]:
svar2 = 3 * x
svar2

array([12,  9])

* (d) Beräkna 5x+3x.

In [48]:
svar3 = svar + svar2
svar3

array([32, 24])

* (e) Beräkna 8x.

In [57]:
svar4 = 8 * x
svar4

array([32, 24])

* (f) Beräkna 4x−x.

In [59]:
fyra = 4 * x
svar5 = fyra - x
svar5

array([12,  9])

* (g) Beräkna x⊤, vilken blir den nya dimensionen efter att transponeringen utförts?

In [88]:
# x.T
# Svar: det ska bli 2x1 efter transponering men x.T funkar inte :(
ny_x = x.reshape(-1, 1)
ny_x

array([[4],
       [3]])

* (h) Är x+x⊤ definierat?

In [90]:
svar6 = x + ny_x
svar6

array([[8, 7],
       [7, 6]])

* (i) Beräkna ∥x∥.

In [93]:
svar7 = np.linalg.norm(x)
svar7

5.0

# Uppgift 10.1.2. Definiera vektorn v enligt nedan.

(a) Vilken dimension har vektorn v?
* Svar: 4x1, v har 4 rader och 1 kolumn
* (b) Beräkna 2v.

In [106]:
v = np.array([3, 7, 0, 11])
svar8 = 2 * v
svar8

array([ 6, 14,  0, 22])

* (c) Beräkna 5v + 2v.

In [109]:
fem = 5 * v
svar9 = fem + svar8
svar9

array([21, 49,  0, 77])

* (d) Beräkna 4v − 2v.

In [112]:
fyra2 = 4 * v
svar10 = fyra2 - svar8
svar10

array([ 6, 14,  0, 22])

* (e) Beräkna v⊤, vilken blir den nya dimensionen efter att transponeringen utförts?
* Svar: 1x4, efter transponering får den 1 rad och 4 kolumner

* (f) Beräkna ∥v∥.

In [117]:
svar11 = np.linalg.norm(v)
svar11

13.379088160259652

# Uppgift 10.1.3. Definiera vektorerna v1 = (4,3,1,5) och v2 = (2,3,1,1).
* (a) Beräkna ∥v1∥.

In [122]:
v1 = np.array([4, 3, 1, 5])
svar12 = np.linalg.norm(v1)
svar12

7.14142842854285

* (b) Beräkna ∥v1 − v2∥

In [128]:
v2 = np.array([2, 3, 1, 1])
svar13 = np.linalg.norm(v1 - v2)
svar13

4.47213595499958

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

# Övningsuppgifter
* Uppgift 10.2.1. Definiera matriserna:

In [300]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])
I = np.array([[1, 0], [0, 1]])

print("Matris A:\n", A)
print("\nMatris B:\n", B)
print("\nMatris C:\n", C)
print("\nMatris D:\n", D)
print("\nMatris E:\n", E)
print("\nMatris I:\n", I)

Matris A:
 [[ 2  1 -1]
 [ 1 -1  1]]

Matris B:
 [[ 4 -2  1]
 [ 2 -4 -2]]

Matris C:
 [[1 2]
 [2 1]]

Matris D:
 [[3 4]
 [4 3]]

Matris E:
 [[1]
 [2]]

Matris I:
 [[1 0]
 [0 1]]


* (a) 2A

In [150]:
svar14 = 2 * A
svar14

array([[ 4,  2, -2],
       [ 2, -2,  2]])

* (b) B −2A

In [153]:
svar15 = B - svar14
svar15

array([[ 0, -4,  3],
       [ 0, -2, -4]])

* (c) 3C −2E

In [156]:
tre_c = 3 * C
two_e = 2 * E
svar16 = tre_c - two_e
svar16

array([[ 1,  4],
       [ 2, -1]])

* (d) 2D −3C

In [161]:
two_d = 2 * D
svar17 = two_d - tre_c
svar17

array([[3, 2],
       [2, 3]])

* (e) D⊤ +2D

In [164]:
transponera_d = D.T
svar18 = transponera_d + two_d
svar18

array([[ 9, 12],
       [12,  9]])

* (f) 2C⊤ −2D⊤

In [179]:
transponera_c = C.T
cT2 = 2 * transponera_c
dT2 = 2 * transponera_d
svar19 = cT2 - dT2
svar19

array([[-4, -4],
       [-4, -4]])

* (g) A⊤ −B

In [231]:
transponera_a = A.T
svar20 = np.dot(transponera_a, B)
svar20

array([[10, -8,  0],
       [ 2,  2,  3],
       [-2, -2, -3]])

* (h) AC

In [233]:
#svar21 = A * C
svar21_test = np.dot(A, C)
#svar21
svar21_test

# Ingen aning, har försökt med allt typ...

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

* (i) CD

In [198]:
svar22 = C * D
svar22

array([[3, 8],
       [8, 3]])

* (j) CB

In [215]:
svar23 = np.dot(C, B)
svar23

array([[  8, -10,  -3],
       [ 10,  -8,   0]])

* (k) CI

In [204]:
svar24 = C * I
svar24

array([[1, 0],
       [0, 1]])

* (l) AB⊤

In [213]:
transponera_b = B.T
svar25 = np.dot(A, transponera_b)
svar25

array([[5, 2],
       [7, 4]])

# Uppgift 10.2.2. Definiera matrisen

In [240]:
A_A = np.array([[2, 3, 4], [5, 4, 1]])
A_A

array([[2, 3, 4],
       [5, 4, 1]])

* Beräkna AAT.

In [258]:
aT = A_A.T
svar26 = np.dot(A, aT)
svar26

array([[ 3, 13],
       [ 3,  2]])

# Uppgift 10.2.3. Definiera matriserna

In [261]:
A_A_A = np.array([[1, 2], [2, 4]])
B_B_B = np.array([[2, 1], [1, 3]])
C_C_C = np.array([[4, 3], [0, 2]])

print("Matris A:\n", A_A_A)
print("\nMatris B:\n", B_B_B)
print("\nMatris C:\n", C_C_C)

Matris A:
 [[1 2]
 [2 4]]

Matris B:
 [[2 1]
 [1 3]]

Matris C:
 [[4 3]
 [0 2]]


In [298]:
A_B = np.dot(A_A_A, B_B_B)
A_C = np.dot(A_A_A, C_C_C)
svar27 = A_B == A_C
svar28 = B_B_B == C_C_C
print("Is A equal to B?\n:", svar27)
print("\n Is B equal to C?\n:", svar28)

Is A equal to B?
: [[ True  True]
 [ True  True]]

 Is B equal to C?
: [[False False]
 [False False]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [191]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [193]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [195]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
